sonar.projectKey=xkior
sonar.organization=xKioe
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.tests=cypress,src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.js,**/*.test.ts,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
